name: Deploy AppEngine

on: push

jobs:
  deploy-appengine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/variable-substitution@v1
        with:
          files: ./appengine/app.yaml
        env:
          env_variables.RAW_EML_BUCKET: ${{ secrets.RAW_EML_BUCKET }}
      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: ./appengine/app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
