name: Deploy AppEngine

on: push

jobs:
  deploy-appengine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/variable-substitution@v1
        with:
          files: ./appengine/app.yaml
        env:
          env_variables.RAW_EML_BUCKET: ${{ secrets.RAW_EML_BUCKET }}
      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: ./appengine/app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
  deploy-firebase-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_BASE64 }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT }}
          PROJECT_PATH: ./firebase
